#
# ltsvを動的に作るようにする
#
# * http://www.pitecan.com/news.ltsv でニュースのltsvを取得
# * http://www.pitecan.com/gear.ltsv?name=Gear&title=masuiで
#   http://gyazz.masuilab.com/Gear/masui のltsvリストを取得する
#

# リストが出るかどうか
test:
	ruby gear.ltsv
