#!/usr/bin/env ruby
# -*- coding: utf-8 -*-
# -*- ruby -*-
#

require 'rubygems'
require 'rss'
require 'open-uri'
require 'hpricot'

#
# 取得したフィードを配列で返す。
# フィードが無い場合は空配列を返す。
# 指定したURLが無効な場合はnilを返す。
#
def feeds(url)
  list = []
  begin
    server = open(url)
  rescue
    return nil
  end
  links = Hpricot(server).search('link')
  links.each { |link|
    if link.attributes['type'] == 'application/rss+xml' ||
        link.attributes['type'] == 'application/atom+xml' then
      rss = link.attributes['href']
      if rss !~ /^http:/ then
        if rss =~ /^\// then
          url =~ /(http:\/\/[^\/]+)\//
          rss = $1 + '/' + rss.sub(/^\//,'')
        else
          url.sub(/\/$/,'')
          rss = url + '/' + rss.sub(/^\.\//,'')
        end
      end
      content = ''
      open(rss){ |f|
        content = f.read
      }
      
      rss = nil
      begin
        rss = RSS::Parser::parse(content)
      rescue RSS::InvalidRSSError
        rss = RSS::Parser::parse(content,false)
      end
      if rss then
        rss.items.each { |u|
          next if u.title =~ /^PR:/ || u.title =~ /^【PR】/ || u.title =~ /^【広告特集】/ || u.title =~ /^AD:/
          list << "url:#{u.link}\ttitle:#{u.title}"
        }
      else
        content.each_with_index { |line,i|
          while line.sub!(/<link>([^<]*)<\/link>/,'') do
            list << "url:#{$1}\t記事#{i}"
          end
          while line.sub!(/<link.*href="(.*?)"/,'') do
            list << "url:#{$1}\t記事#{i}"
          end
        }
      end
      break
    end
  }
  return list
end

def news(title,url)
  list = feeds(url)
  puts " title:#{title}\turl:#{url}"
  if list then
    list.each { |entry|
      puts "  #{entry}"
    }
  end
end

puts "title:ニュース"

news('朝日新聞','http://www.asahi.com/')
news('日本経済新聞','http://www.nikkei.com/')
news('読売新聞','http://www.yomiuri.co.jp/')
news('毎日新聞','http://mainichi.jp/')
news('産経新聞','http://sankei.jp.msn.com')
news('ITmedia','http://www.itmedia.co.jp')


